// ═══ 前后端共享错误码 ═══

export const ErrorCode = {
  USERNAME_EXISTS:      -100,
  INVALID_CREDENTIALS:  -101,
  ACCOUNT_DISABLED:     -103,
  TOKEN_EXPIRED:        -104,
  INVALID_USERNAME:     -105,
  WEAK_PASSWORD:        -106,
  INVALID_INVITE_CODE:  -107,
  PHONE_NOT_FOUND:      -200,
  COLLISION_DETECTED:   -201,
  CONTACT_PROTECTED:    -202,
  CONFIRM_MISMATCH:     -203,
  FIELD_LOCKED:         -204,
  UNSUPPORTED_FORMAT:   -300,
  FILE_TOO_LARGE:       -301,
  NO_PHONE_COLUMN:      -302,
  IMPORT_TOKEN_EXPIRED: -303,
  FORBIDDEN:            -400,
  UNAUTHORIZED:         -401,
  RATE_LIMITED:         -402,
  BAD_REQUEST:          -403,
  NOT_FOUND:            -404,
  INTERNAL_ERROR:       -500,
} as const

export const ErrorMsg: Record<number, string> = {
  [-100]: 'Username already exists',
  [-101]: 'Invalid credentials',
  [-103]: 'Account disabled',
  [-104]: 'Token expired',
  [-105]: 'Invalid username (3-20 chars, letters/numbers/underscore only)',
  [-106]: 'Weak password (requires uppercase, lowercase and number)',
  [-107]: 'Invalid, fully used, or expired invite code',
  [-200]: 'Phone number not found',
  [-201]: 'Collision detected',
  [-202]: 'Contact is protected',
  [-203]: 'Confirm word mismatch',
  [-204]: 'Field is locked',
  [-300]: 'Unsupported file format',
  [-301]: 'File too large',
  [-302]: 'No phone column found',
  [-303]: 'Import token expired',
  [-400]: 'Forbidden',
  [-401]: 'Unauthorized',
  [-402]: 'Rate limited',
  [-403]: 'Bad Request',
  [-404]: 'Not Found',
  [-500]: 'Internal server error',
}
