name: Deploy to Cloudflare Workers

on:
  workflow_dispatch: {}
  push: &trigger
    branches: [ "main" ]
    paths: [ "api/**", ".github/workflows/api.yaml" ]
  pull_request: *trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: ./api } }
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - uses: cloudflare/wrangler-action@v3
        name: Apply D1 Migrations
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          workingDirectory: api
          command: d1 migrations apply crm-api --remote

      - uses: cloudflare/wrangler-action@v3
        name: Deploy Workers
        env:
          WRANGLER_LOG: debug
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          workingDirectory: api
          command: deploy
